# Generated by Django 5.2 on 2025-06-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("value_investment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DAILY_LIST",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_str", models.TextField(default="")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
