#!/usr/bin/env bash
#
# broker_reports Google Drive OAuth 設定精靈
# 帶你在 Google Cloud Console 建立憑證，讓 tools/broker_reports.py 能讀
# 朋友分享的雲端硬碟資料夾。generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Google Drive OAuth 憑證設定（讓 broker_reports.py 能讀共用資料夾）
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# 讓精靈無論從哪裡執行，都以 repo 根為工作目錄（credentials.json 要放這裡）。
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# 選一個能跑的 Python（優先專案 venv）。
PYBIN=".venv/bin/python"
[[ -x "$PYBIN" ]] || PYBIN="venv/bin/python"
[[ -x "$PYBIN" ]] || PYBIN="python3"

banner "券商報告 · Google Drive 授權設定"

# ── Stage 1：建立 / 選擇 Google Cloud 專案 ────────────────────────────────
stage "Google Cloud — 建立專案"
say "券商報告工具用 Google Drive API 讀你朋友分享的資料夾。"
say "第一步是有一個 Google Cloud 專案（免費，純為拿 API 憑證）。"
open_url "https://console.cloud.google.com/projectcreate"
step "在頁面按「建立專案」，名稱隨意（例如 stock-broker-reports），按「建立」。"
step "等右上角通知建立完成後，確認頁面左上已切到這個新專案。"
pause "專案建立好、且已選為目前專案了嗎？按 Enter 繼續"

# ── Stage 2：啟用 Drive API ──────────────────────────────────────────────
stage "啟用 Google Drive API"
say "要讓專案能呼叫 Drive，需在「API 程式庫」啟用它。"
open_url "https://console.cloud.google.com/apis/library/drive.googleapis.com"
step "確認頂端專案是剛剛建立的那個。"
step "按藍色的「啟用」(Enable) 按鈕，等它變成「管理」(Manage) 即完成。"
pause "Drive API 顯示已啟用了嗎？按 Enter 繼續"

# ── Stage 3：設定 OAuth 同意畫面 ──────────────────────────────────────────
stage "OAuth 同意畫面"
say "因為用「你的帳號」去讀資料，Google 要求先設定同意畫面並把自己列為測試者。"
open_url "https://console.cloud.google.com/apis/credentials/consent"
step "User Type 選「外部」(External)，按「建立」。"
step "App name 隨意填（例 stock-broker-reports），User support email 選你的信箱。"
step "Developer contact 也填你的信箱，其餘可留空，一路「儲存並繼續」。"
step "走到「測試使用者」(Test users) 那步，按「ADD USERS」，加入你自己的 Google 信箱。"
note "只把自己加為測試者即可，不需送審（不對外發布）。"
pause "同意畫面已設定、且你的信箱已在測試使用者清單裡了嗎？按 Enter 繼續"

# ── Stage 4：建立 OAuth 用戶端 ID 並下載 credentials.json ──────────────────
stage "建立 OAuth 用戶端 ID"
say "現在產生桌面應用程式類型的憑證，下載成 credentials.json。"
open_url "https://console.cloud.google.com/apis/credentials"
step "按上方「+ 建立憑證」→「OAuth 用戶端 ID」。"
step "應用程式類型選「桌面應用程式」(Desktop app)，名稱隨意，按「建立」。"
step "彈窗出現後按「下載 JSON」，把檔案存下來（通常在「下載」資料夾）。"
say "接著把它放到專案根目錄並命名為 credentials.json —"
note "專案根目錄：$REPO_ROOT"
note "例：mv ~/Downloads/client_secret_*.json \"$REPO_ROOT/credentials.json\""
pause "已把 credentials.json 放到專案根目錄了嗎？按 Enter 讓精靈檢查"

# 驗證檔案存在且像個 OAuth client secret。
if [[ ! -f "credentials.json" ]]; then
  warn "在 $REPO_ROOT 找不到 credentials.json。"
  say "請確認檔名正確（credentials.json）且放在上面那個路徑，再重跑本精靈。"
  exit 1
fi
if ! grep -q "client_id" credentials.json 2>/dev/null; then
  warn "credentials.json 內容看起來不像 OAuth 用戶端憑證（找不到 client_id）。"
  say "請確認下載的是「OAuth 用戶端 ID」的 JSON，而非其他金鑰類型。"
  exit 1
fi
printf '  %s✓ 找到 credentials.json%s\n' "$GREEN" "$RESET"
note "（credentials.json 與稍後產生的 token.json 已被 .gitignore 排除，不會被 commit）"

# ── Stage 5：第一次授權（產生 token.json）──────────────────────────────────
stage "第一次授權"
say "現在跑一次同步，會開瀏覽器讓你登入並同意授權，成功後自動存下 token.json。"
warn "登入時選「你自己的」Google 帳號（就是被朋友分享資料夾、且剛加為測試者的那個）。"
warn "若出現「Google 尚未驗證這個應用程式」，點「進階」→「前往（不安全）」即可（這是你自己的測試 App）。"
if confirm "現在開始授權並做第一次同步？"; then
  say "執行：$PYBIN tools/broker_reports.py --sync"
  if "$PYBIN" tools/broker_reports.py --sync; then
    printf '  %s✓ 授權 + 首次同步完成%s\n' "$GREEN" "$RESET"
  else
    warn "同步指令回報錯誤。可稍後手動重跑：$PYBIN tools/broker_reports.py --sync"
    SKIPPED+=("重跑同步：$PYBIN tools/broker_reports.py --sync")
  fi
else
  SKIPPED+=("授權 + 首次同步：$PYBIN tools/broker_reports.py --sync")
  note "稍後可自行執行上面那行完成授權。"
fi

# ── Stage 6：驗證索引 ─────────────────────────────────────────────────────
stage "驗證"
say "看一下本地索引現況（應顯示已索引的個股/產業報告筆數）。"
"$PYBIN" tools/broker_reports.py --stats || warn "讀取索引狀態失敗。"
say ""
say "之後查詢範例："
note "  $PYBIN tools/broker_reports.py --stock 2330"
note "  $PYBIN tools/broker_reports.py --sector 記憶體"
note "  更新索引（有新報告時）：$PYBIN tools/broker_reports.py --sync"

finish
